// src/views/Blog/index.vue
<script>
import BaseHeadingH1 from '../../components/base/BaseHeadingH1';

export default {
  name: 'Blog',
  components: {
    BaseHeadingH1,
  },
  data() {
    return {
      articles: [],
    };
  },
  created() {
    this.fetchArticles();
  },
  methods: {
    async fetchArticles() {
      const res = await fetch('https://dev.to/api/articles?username=drewclem', {
        method: 'GET',
      })
        .then((res) => res.json())
        .then((data) => (this.articles = data));

      return res;
    },
  },
};
</script>

<template>
  <div>
    <BaseHeadingH1 class="capitalize">{{ $route.name }}</BaseHeadingH1>

    <div class="md:w-3/4">
      <article
        class="pb-8 mb-8 border-b border-gray-200"
        v-for="article in articles"
        :key="article.id"
      >
        <p class="text-red-500 text-sm mb-1">
          {{ article.readable_publish_date }}
        </p>

        <h2 class="text-lg font-bold font-display mb-4 ">
          {{ article.title }}
        </h2>

        <p class="opacity-75 mb-2" v-html="article.description" />

        <router-link
          class="text-red-500 opacity-75 text-sm hover:opacity-100 underline font-display"
          :to="`blog/${article.slug}`"
          >Read More</router-link
        >
      </article>
    </div>
  </div>
</template>

// src/routes/blog/+page.svelte
<script>
  /**
* @type {any[]}
*/
  let articles = []
  async function fetchArticles() {
    const res = await fetch('https://dev.to/api/articles?username=drewclem&state=all', {
      method: 'GET'
    })

    const data = await res.json()

    articles = data
  }

  fetchArticles()
</script>

<div class="relative">
	<div class="w-4 h-4 lg:w-6 lg:h-6 bg-red-500 absolute" />
	<h1 class="text-4xl lg:text-4xl font-display font-bold ml-4 pt-1 lg:ml-6 lg:pt-3 mb-8">Blog</h1>
</div>

<section class="md:w-3/4">
	{#each articles as article}
		<article class="pb-8 mb-8 border-b border-gray-100">
			<p class="text-red-600 text-sm mb-1">{article.readable_publish_date}</p>
			<h2 class="text-lg font-bold font-display mb-4">{article.title}</h2>

			<div class="mb-2 opacity-75 ">{article.description}</div>

			<a href={`blog/${article.slug}`} class="text-red-600 text-sm underline font-display">
				Read More
			</a>
		</article>
	{/each}
</section>
